### ISSUE TITLE
Could you please make your repository private?

### ISSUE THREAD

**Issue by keithw** [huangrt01/TCP-Lab#1]
We are trying to avoid temptation for the students taking the course. Thanks much.

**Comment by huangrt01** [comment]
I delete the "cs144" marks from the repository name and the README, ensuring that this repo won't get searched through the Github or Google page.

**Comment by fzyzcjy** [comment]
@keithw Hi the official repo seems to be deleted :( Is there any backups? Thanks very much!

**Comment by keithw** [comment]
@fzyzcjy We asked @huangrt01 to please make his solutions private to avoid temptation for other students taking the course, and he refused (see above), so I had to make them private for now. I'd love for the general academic community to benefit from our work in making these labs, but my trust that others could be persuaded to help preserve their educational value may have been naive.

**Comment by fzyzcjy** [comment]
@keithw So sad to hear that 😭 I am a senior CS student and want to do these labs by myself, since you know, they can greatly deepen my knowledge in networking. 

By the way, in my humble opinion, Stanford is known to have super powerful code plagiarism detectors. So since this repository is public, maybe it can be added into the detector and anyone copying the code will be found?

**Comment by keithw** [comment]
@huangrt01 We would really just prefer that you honor the spirit of the assignment, and all the work that went into making it, and make your solutions private. Then everybody can benefit from being able to do these labs.

**Comment by huangrt01** [comment]
I think opensourcing is irrelevant to whether someone make their solutions public. In fact, the only way to prevent someone show their solutions is never making the assignment public. For example, when I’m doing this lab, I search the Github and find at least three complete solutions, and I believe they still exist today. If you make the assignment public again, there must be increasing answers. See the famous CSAPP, MIT 6.824 lab, no one can delete the answers stored in a distributed way.


| |
huangrt01
邮箱：huangrt01@163.com
|

Signature is customized by Netease Mail Master

On 09/08/2020 10:09, Keith Winstein wrote:

@huangrt01 We would really just prefer that you honor the spirit of the assignment, and all the work that went into making it, and make your solutions private. Then everybody can benefit from being able to do these labs.

**Comment by keithw** [comment]
Hi, I went to MIT and now teach at Stanford and subscribe to the ideal of making my assignments open to the world. I'm glad you benefited from them -- my course assistants and I worked hard on making them! I understand why people post solutions; it's a lot of work to solve and I don't blame you for being proud of them and wanting to show others your elegant approach. You're not the first person who has posted solutions, and in the past, we (Stanford CS144) have written emails politely to people who post public solutions and asked if they would be willing to make their solutions private. Everybody until now has agreed! I think the authors of textbooks and exams do the same thing with people who feel proud enough of their solutions to post those publicly.

Let me say this again to be clear: To the best of my knowledge, you are the **first person** who has ever refused a polite request from Stanford CS144 to remove the solutions to our lab assignments. I will probably write to the other people; it's not like I search for these every day.

So frankly, I don't see this (yet) as a societal problem -- I see a @huangrt01 problem. We worked hard on these labs, and I'd love there to be a community of people interested in these CS144 labs around the Internet, and I would love you to be part of it, but right now you just seem like some rando from Tunghai University and TikTok who benefited from my work yet is inexplicably declining our polite request to keep solutions private. (Would you do the same if a textbook author wrote to you?)

My teaching assistants and I are going to keep improving these labs every year to make them better, and I'm going to keep making assignments for my other classes. If you're really correct that there are just too many jerks on the Internet to make the "polite email" approach successful anymore, I may have to reconsider my public ideals and make the future versions private to my students at Stanford. I'm writing this long message because I want to make my thinking clear here about why I want you to reconsider, and I want to be able to point people to this thread when they ask me why I made the labs and their future versions private. I will be sad about this and I suspect you might be too. Frankly, I hope you will change your mind -- it's not too late.

Thanks for your consideration.

Sincerely,
Keith Winstein
Assistant Professor of Computer Science
Assistant Professor of Electrical Engineering (by courtesy)
Stanford University

**Comment by huangrt01** [comment]
Dear professor, 
    I consider your proposal proper and agree with most of your statements, except for the fact that “I am the first person who has ever refused a polite request”. I don’t see "Everybody until now has agreed!”.  The following repos https://github.com/gcidart/cs144, https://github.com/KshZh/cs144, https://github.com/conanhujinming/Stanford-CS144-Labs still exist, two of them created before my repo. Their repos are titled with blatant CS144 and have a higher possibility to be found by the students. Maybe you overlook them, or they overlook your email so I become the first person to refuse.
    I know making my solutions private do no harm to me, and I will make it private after the fact seems clearer to me.


On 09/8/2020 13:16，Keith Winstein<notifications@github.com> wrote：

Hi, I went to MIT and now teach at Stanford and subscribe to the ideal of making my assignments open to the world. I'm glad you benefited from them -- my course assistants and I worked hard on making them! I understand why people post solutions; it's a lot of work to solve and I don't blame you for being proud of them and wanting to show others your elegant approach. You're not the first person who has posted solutions, and in the past, we (Stanford CS144) have written emails politely to people who post public solutions and asked if they would be willing to make their solutions private. Everybody until now has agreed! I think the authors of textbooks and exams do the same thing with people who feel proud enough of their solutions to post those publicly.

Let me say this again to be clear: To the best of my knowledge, you are the first person who has ever refused a polite request from Stanford CS144 to remove the solutions to our lab assignments. I will probably write to the other people; it's not like I search for these every day.

So frankly, I don't see this (yet) as a societal problem -- I see a @huangrt01 problem. We worked hard on these labs, and I'd love there to be a community of people interested in these CS144 labs around the Internet, and I would love you to be part of it, but right now you just seem like some rando from Tunghai University and TikTok who benefited from my work yet is inexplicably declining our polite request to keep solutions private. (Would you do the same if a textbook author wrote to you?)

My teaching assistants and I are going to keep improving these labs every year to make them better, and I'm going to keep making assignments for my other classes. If you're really correct that there are just too many jerks on the Internet to make the "polite email" approach successful anymore, I may have to reconsider my public ideals and make the future versions private to my students at Stanford. I'm writing this long message because I want to make my thinking clear here about why I want you to reconsider, and I want to be able to point people to this thread when they ask me why I made the labs and their future versions private. I will be sad about this and I suspect you might be too. Frankly, I hope you will change your mind -- it's not too late.

Thanks for your consideration.

Sincerely,
Keith Winstein
Assistant Professor of Computer Science
Assistant Professor of Electrical Engineering (by courtesy)
Stanford University

**Comment by keithw** [comment]
As I said, I will probably write to the other people; it's not like I search for these every day and was not aware of them. But the decision what to do about your repository is yours.
