### ISSUE TITLE
webget is timeout

### ISSUE THREAD

**Issue by carlclone** [huangrt01/TCP-Lab#2]
hello , i am stuck with a problem that the t_webget test always timeout in the cs144 provided vm_image cs144_vm.ova , but works in my other ubuntu virtual machine , and the problem also occur by running your code , i wonder if you encounter the same problem ?

here is some debug info:
```
28/166 Test: t_webget
Command: "/home/cs144/cs144/tests/webget_t.sh"
Directory: /home/cs144/cs144/build
"t_webget" start time: Jul 11 15:51 PDT
Output:
----------------------------------------------------------
DEBUG: Network interface has Ethernet address ca:ef:fd:10:10:5a and IP address 169.254.10.9
DEBUG: Connecting to 104.196.238.229:80... done.
DEBUG: Outbound stream to 104.196.238.229:80 finished (55 bytes still in flight).
DEBUG: Outbound stream to 104.196.238.229:80 has been fully acknowledged.
<end of output>
Test time =  10.01 sec
```

**Comment by huangrt01** [comment]
I sometimes have the DEBUG information, but I can pass the webget test in my virtual machine. I think it's related to your network environment and your input web url. Because the webget is a relatively easy-to-pass test, it is irrelevant to the correctness of your code if you can pass all the other tests. The last half test is harder.
